// Autogenerated from Pigeon (v26.1.7), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

func deepEqualsMessages(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case is (Void, Void):
    return true

  case let (cleanLhsHashable, cleanRhsHashable) as (AnyHashable, AnyHashable):
    return cleanLhsHashable == cleanRhsHashable

  case let (cleanLhsArray, cleanRhsArray) as ([Any?], [Any?]):
    guard cleanLhsArray.count == cleanRhsArray.count else { return false }
    for (index, element) in cleanLhsArray.enumerated() {
      if !deepEqualsMessages(element, cleanRhsArray[index]) {
        return false
      }
    }
    return true

  case let (cleanLhsDictionary, cleanRhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard cleanLhsDictionary.count == cleanRhsDictionary.count else { return false }
    for (key, cleanLhsValue) in cleanLhsDictionary {
      guard cleanRhsDictionary.index(forKey: key) != nil else { return false }
      if !deepEqualsMessages(cleanLhsValue, cleanRhsDictionary[key]!) {
        return false
      }
    }
    return true

  default:
    // Any other type shouldn't be able to be used with pigeon. File an issue if you find this to be untrue.
    return false
  }
}

func deepHashMessages(value: Any?, hasher: inout Hasher) {
  if let valueList = value as? [AnyHashable] {
     for item in valueList { deepHashMessages(value: item, hasher: &hasher) }
     return
  }

  if let valueDict = value as? [AnyHashable: AnyHashable] {
    for key in valueDict.keys { 
      hasher.combine(key)
      deepHashMessages(value: valueDict[key]!, hasher: &hasher)
    }
    return
  }

  if let hashableValue = value as? AnyHashable {
    hasher.combine(hashableValue.hashValue)
  }

  return hasher.combine(String(describing: value))
}

    

enum BatteryState: Int {
  case charging = 0
  case discharging = 1
  case full = 2
  case unknown = 3
}

enum ThermalState: Int {
  /// nominal value
  case safe = 0
  /// device is getting warm, but not under throttling
  case fair = 1
  /// device is getting warm and performance is throttled
  case serious = 2
  /// performance is throttled, device is too hot
  case critical = 3
  /// unknown state
  case unknown = 4
}

enum ConnectivityType: Int {
  case ethernet = 0
  case wifi = 1
  case mobile2g = 2
  case mobile3g = 3
  case mobile4g = 4
  case mobile5g = 5
  case none = 6
  case unknown = 7
}

/// Generated class from Pigeon that represents data sent in messages.
struct Connectivity: Hashable {
  var type: ConnectivityType
  var wifiSignalStrength: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> Connectivity? {
    let type = pigeonVar_list[0] as! ConnectivityType
    let wifiSignalStrength: Int64? = nilOrValue(pigeonVar_list[1])

    return Connectivity(
      type: type,
      wifiSignalStrength: wifiSignalStrength
    )
  }
  func toList() -> [Any?] {
    return [
      type,
      wifiSignalStrength,
    ]
  }
  static func == (lhs: Connectivity, rhs: Connectivity) -> Bool {
    return deepEqualsMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashMessages(value: toList(), hasher: &hasher)
  }
}

private class MessagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return BatteryState(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return ThermalState(rawValue: enumResultAsInt)
      }
      return nil
    case 131:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return ConnectivityType(rawValue: enumResultAsInt)
      }
      return nil
    case 132:
      return Connectivity.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class MessagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? BatteryState {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? ThermalState {
      super.writeByte(130)
      super.writeValue(value.rawValue)
    } else if let value = value as? ConnectivityType {
      super.writeByte(131)
      super.writeValue(value.rawValue)
    } else if let value = value as? Connectivity {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class MessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MessagesPigeonCodecWriter(data: data)
  }
}

class MessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MessagesPigeonCodec(readerWriter: MessagesPigeonCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol EcoModeApi {
  func getPlatformInfo() throws -> String
  func getBatteryLevel() throws -> Double
  func getBatteryState() throws -> BatteryState
  func isBatteryInLowPowerMode() throws -> Bool
  func getThermalState() throws -> ThermalState
  func getProcessorCount() throws -> Int64
  func getTotalMemory() throws -> Int64
  func getFreeMemory() throws -> Int64
  func getTotalStorage() throws -> Int64
  func getFreeStorage() throws -> Int64
  func getEcoScore() throws -> Double?
  func getConnectivity() throws -> Connectivity
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class EcoModeApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `EcoModeApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: EcoModeApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let getPlatformInfoChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_eco_mode.EcoModeApi.getPlatformInfo\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getPlatformInfoChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getPlatformInfo()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getPlatformInfoChannel.setMessageHandler(nil)
    }
    let getBatteryLevelChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_eco_mode.EcoModeApi.getBatteryLevel\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getBatteryLevelChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getBatteryLevel()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getBatteryLevelChannel.setMessageHandler(nil)
    }
    let getBatteryStateChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_eco_mode.EcoModeApi.getBatteryState\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getBatteryStateChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getBatteryState()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getBatteryStateChannel.setMessageHandler(nil)
    }
    let isBatteryInLowPowerModeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_eco_mode.EcoModeApi.isBatteryInLowPowerMode\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      isBatteryInLowPowerModeChannel.setMessageHandler { _, reply in
        do {
          let result = try api.isBatteryInLowPowerMode()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      isBatteryInLowPowerModeChannel.setMessageHandler(nil)
    }
    let getThermalStateChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_eco_mode.EcoModeApi.getThermalState\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getThermalStateChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getThermalState()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getThermalStateChannel.setMessageHandler(nil)
    }
    let getProcessorCountChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_eco_mode.EcoModeApi.getProcessorCount\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getProcessorCountChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getProcessorCount()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getProcessorCountChannel.setMessageHandler(nil)
    }
    let getTotalMemoryChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_eco_mode.EcoModeApi.getTotalMemory\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getTotalMemoryChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getTotalMemory()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getTotalMemoryChannel.setMessageHandler(nil)
    }
    let getFreeMemoryChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_eco_mode.EcoModeApi.getFreeMemory\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getFreeMemoryChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getFreeMemory()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getFreeMemoryChannel.setMessageHandler(nil)
    }
    let getTotalStorageChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_eco_mode.EcoModeApi.getTotalStorage\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getTotalStorageChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getTotalStorage()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getTotalStorageChannel.setMessageHandler(nil)
    }
    let getFreeStorageChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_eco_mode.EcoModeApi.getFreeStorage\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getFreeStorageChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getFreeStorage()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getFreeStorageChannel.setMessageHandler(nil)
    }
    let getEcoScoreChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_eco_mode.EcoModeApi.getEcoScore\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getEcoScoreChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getEcoScore()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getEcoScoreChannel.setMessageHandler(nil)
    }
    let getConnectivityChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_eco_mode.EcoModeApi.getConnectivity\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getConnectivityChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getConnectivity()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getConnectivityChannel.setMessageHandler(nil)
    }
  }
}
